name: selenium3-java

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 3 * * *'

jobs:
  test:

    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        browser: [chrome, firefox]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache Gradle packages
      uses: actions/cache@v1
      if: matrix.os == 'ubuntu-latest'
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Grant execute permission for gradlew
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
      run: chmod +x gradlew
    - name: Test with Gradle (UN*X)
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
      run: ./gradlew cleanTest test
      env:
        BROWSER: ${{ matrix.browser }}
    - name: Test with Gradle (Windows)
      if: matrix.os == 'windows-latest'
      run: .\gradlew.bat cleanTest test
      env:
        BROWSER: ${{ matrix.browser }}
